### ISSUE TITLE
Add a primal-dual interior point SDP solver

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#387]
I have a working implementation of a primal-dual interior point solver. I'd like to open up a discussion for comments about the API and implementation: https://github.com/stephentu/mlpack/compare/ip

There is some code duplication currently between this code and `LRSDP`. My goal is to present a single interface for SDP (which is the `SDP`) class, and then have `LRSDP` take in an `SDP` object as input (much like the `PrimalDualSolver` does now). 

For this to be practical I think there are a few optimizations left that need to be implemented (especially the predictor-corrector step). But it's OK for now and we can add optimizations after we agree upon and flush out the API.

**Comment by rcurtin** [comment]
Sure, I'll start poking through in the next couple of days and add comments as I have time.

**Comment by rcurtin** [comment]
Comments on lin_alg.hpp/lin_alg.cpp (maybe I can comment on the diffs you linked?  I didn't see an easy way).  Many of my comments may be somewhat pedantic, so, hopefully they are not too annoying...

* Any reason for the name `Svec`/`Smat`/`SvecIndex`?  I'm not recognizing the name.
* Inlining `SvecIndex()` is probably a good idea, though it requires it to be in the header file.
* GNU libc provides `M_SQRT2` and `M_SQRT1_2`.  If not using GNU libc, you can define it by hand, like in `src/mlpack/prereqs.hpp` for `M_PI`.
* I haven't thought about how to accelerate `SymKronId()` but I'm pretty sure it's possible.

**Comment by rcurtin** [comment]
Comments on `sdp.hpp`/`sdp.cpp`:

* The basic architecture here is that `SDP` is an object representing the problem, which is then solved by `PrimalDualSolver`.  I like this architecture, but we should probably adapt `LRSDP` to take `SDP` objects also, instead of holding all the information about the problem internally.  This allows us, at  the higher level, to provide interfaces like `LMNN<LRSDP>` or `LMNN<PrimalDualSolver>`.

* Why provide `N2Bar()`?  The `SDP` class doesn't actually use it.

* I don't know that I agree with storing both a sparse and dense objective.  I'd actually lean towards templatizing `SDP` so you get `SDP<ObjectiveMatrixType>` or something.  This will accelerate code in the solver because you won't have to check if there is a sparse or dense objective.  (A smart compiler could actually figure that out at compile time fairly easily, but I'm not sure that gcc actually will.)

* If you're highly against templatizing the objective matrix type, you can avoid holding `hasModifiedDenseObjective` and `hasModifiedSparseObjective` like this:

```
bool HasSparseObjective() const { return !(sparseC.n_elem == 0); }
bool HasDenseObjective() const { reutrn !(denseC.n_elem == 0); }
```

It's also worth pointing out that the current architecture allows the user to get into really weird situations if they call `SparseC()` then also `DenseC()` for some reason.  The solution I just wrote doesn't help that situation at all.

Comments on `primal_dual.hpp`/`primal_dual.cpp`:

* I don't know what a lot of the parameters to the optimizer are, but I'm assuming you're planning to add some comments to the definitions of those parameters at some point.

* `Optimize()` returns a `std::pair<bool, double>`.  The `bool` is the success indicator and the `double` is the objective.  Other optimizers just return the final objective, though.  It seems like `false` is only returned when the solver does not converge in the specified number of iterations.  I'm not sure any higher-level code will ever use that information, though, so I don't know how useful it is to return both a `bool` and a `double` as opposed to just the objective value.

* Ok, this is hopefully the most pedantic thing I write, and I don't mean to be moving the goalposts or anything, but it looks like this was never written in the style guide (I'll update it in a moment).  Variable naming should preferably avoid underscores and use camelcase instead (i.e. `dualInfeas` instead of `dual_infeas`), for the sake of consistency.  I can change these after we merge it in; I don't like forcing trivial things like this onto other people's contributions, but I would like the code in master to eventually look like that.

* I think templatizing `SDP` to have a sparse or dense objective function will condense the code in `Optimize()` significantly; no need for all those conditionals.

* line 203: `rd = - sz - Asparse.t() * ...`: is that a typo?  It's odd to see a negative sign separated from the argument like that, so I just wanted to check.

* You can allow (basically) unlimited iterations by modifying line 191 like so:

```for (size_t iteration = 1; iteration != maxIterations; ++iteration)```

and then a user can pass `maxIterations = 0` for no iteration limit.

* `DenseFromSparse()` seems overkill to me; you can just use `arma::mat()` instead.  Also, it might be worth templatizing `Svec()` to work with sparse matrices.  I'd be happy to do that templatization.

* For the sake of consistency with other mlpack algorithms, I'd choose `initialX` as a parameter name, as opposed to `X0`.

I haven't sat down yet to really go through the Armadillo expressions and see if I can accelerate them, but I'll do that once you take a look through my comments and decide what should change (if anything).  As always, if I write something you disagree with, feel free to start a discussion.  I think more robust discussion leads to more robust abstractions. :)

**Comment by stephentu** [comment]
This is more of a note for myself, but `SymKronId` can possibly be accelerated using the expression in the appendix of http://dspace.library.cornell.edu/bitstream/1813/9038/1/TR001154.pdf

**Comment by stephentu** [comment]
> Any reason for the name Svec/Smat/SvecIndex? I'm not recognizing the name.

These correspond to the names in the paper (https://www.cs.nyu.edu/overton/papers/pdffiles/pdsdp.pdf) that I'm basing this implementation off of. 

> Inlining SvecIndex() is probably a good idea, though it requires it to be in the header file.

Ok, can I just plop it in the header file or do you prefer `lin_alg_impl.hpp`?

**Comment by stephentu** [comment]
> Why provide N2Bar()? The SDP class doesn't actually use it.

It is used by `PrimalDualSolver::Optimize`

> I don't know that I agree with storing both a sparse and dense objective. I'd actually lean towards templatizing SDP so you get SDP<ObjectiveMatrixType> or something. This will accelerate code in the solver because you won't have to check if there is a sparse or dense objective. (A smart compiler could actually figure that out at compile time fairly easily, but I'm not sure that gcc actually will.)

I'm starting to agree with this, after having written the solver to deal with both. I don't think I've seen a situation yet where we needed both. I think I'll go ahead and template it out. 

> Optimize() returns a std::pair<bool, double>. The bool is the success indicator and the double is the objective. Other optimizers just return the final objective, though. It seems like false is only returned when the solver does not converge in the specified number of iterations. I'm not sure any higher-level code will ever use that information, though, so I don't know how useful it is to return both a bool and a double as opposed to just the objective value.

Honestly, I wrote this for the tests. Basically, since the primal dual method here is unique in that it is able to certify its own optimality, I wanted the test cases to be able to have access to this information. What API would you prefer for communicating this? I'd like to avoid having to write the KKT conditions out for each test case. We could write a free function (something like `CheckKKT`) locally for the test cases. 

> line 203: rd = - sz - Asparse.t() * ...: is that a typo? It's odd to see a negative sign separated from the argument like that, so I just wanted to check.

It's not a typo, but this weirdness will go away once I templatize.

**Comment by rcurtin** [comment]
>> Any reason for the name Svec/Smat/SvecIndex? I'm not recognizing the name.
> These correspond to the names in the paper (https://www.cs.nyu.edu/overton/papers/pdffiles/pdsdp.pdf) that I'm basing this implementation off of.

Ah, okay, I see that now in the comments of `primal_dual.hpp`.  The comments on what the function does are clear anyway, so the question was just to satisfy my curiosity.

>> Why provide N2Bar()? The SDP class doesn't actually use it.
> It is used by `PrimalDualSolver::Optimize`

In this case, I'd suggest that it could be used as a utility function inside of `PrimalDualSolver` or just inlined everywhere.

>> Optimize() returns a std::pair. The bool is the success indicator and the double is the objective. Other optimizers just return the final objective, though. It seems like false is only returned when the solver does not converge in the specified number of iterations. I'm not sure any higher-level code will ever use that information, though, so I don't know how useful it is to return both a bool and a double as opposed to just the objective value.
> Honestly, I wrote this for the tests. Basically, since the primal dual method here is unique in that it is able to certify its own optimality, I wanted the test cases to be able to have access to this information. What API would you prefer for communicating this? I'd like to avoid having to write the KKT conditions out for each test case. We could write a free function (something like CheckKKT) locally for the test cases.

Yeah---I agree with that idea (unless you can think of something better).  I don't see any issue with taking an extra second during the tests to call `CheckKKT()`.

**Comment by rcurtin** [comment]
Anything left to do on this one?  The PR is merged, so I don't know if there was anything else you wanted to address.

**Comment by rcurtin** [comment]
Actually, there is something left to do... it looks like occasionally, the initial Z matrix passed to PrimalDualSolver is not symmetric positive definite:

`[FATAL] PrimalDualSolver::PrimalDualSolver(): initialZ needs to be symmetric positive definite.`

(according to the errors, at least.)  This occurs sometimes in the tests:

http://big.cc.gt.atl.ga.us/job/mlpack%20-%20nightly%20matrix%20build/

It looks like Armadillo 4.000 and older did not support the expression '-arma::sp_mat()'.  I'll take care of backporting that functionality shortly.

**Comment by stephentu** [comment]
Ok I was slightly worried about that-- I think the construction used now is actually just a heuristic. Hence,  i'll just comment out the test which tries to construct a strictly feasible point for maxcut on a random random graph

**Comment by stephentu** [comment]
This should be resolved by 5b8b88c95e161efd977709c303861b9c3b88feb2

**Comment by rcurtin** [comment]
`-arma::sp_mat` backported for Armadillo <= 4.000 in dd5d265 (I suppose I'll find out tonight if I backported it correctly for all Armadillo versions...)

**Comment by stephentu** [comment]
Can we close this issue for now, and open new ones for improvements to the solver?

**Comment by rcurtin** [comment]
I think the tests still failing is a reasonably outstanding issue:

http://big.cc.gt.atl.ga.us/job/mlpack%20-%20nightly%20matrix%20build/arch=linux-amd64,armadillo=armadillo-4.500.0,buildmode=release/730/console

This is the same issue as for the test you commented out.  I'm happy to dig in and try to make initialZ symmetric positive definite, but I am far from the expert in this case...

If you instead want to close this issue and open another one for that, sure, go ahead; I just want to make sure that the failing tests get addressed at some point.

**Comment by stephentu** [comment]
alright, so I believe that there are some starting points for which, despite being positive, result in some poor numerical issues with the algorithm. I worked around this issue in e4330544cb04ac6d2bb38e1372bffd8c6cef6bcb by simply using a more numerically stable starting point (the condition # of some of the random starting points was around 400 FYI). 

to actually solve this problem in general, i'm not sure of how to do this at the moment. there are some sophisticated pre-conditioning techniques to try and make the problem more well behaved. these techniques are far beyond the realm of my knowledge. i think we can leave it for now and wait for the kinds of problems people actually try to solve SDPs with to decide how to proceed.
